server:
    port: 8082

spring:
    application:
        name: JavaRunnerApi

java:
    runner:
        path: C:/projects/disertatie/jars
        jar:
            name: java-runner-1.0-SNAPSHOT.jar
        content:
            separator: \.