server:
  port: 8082

spring:
  application:
    name: JavaServiceApi

java-runner:
  docker:
    buildArgs:
      copyPathArg: COPY_PATH
    container:
      timeoutMilliseconds: 60000

gotty:
  port: 8080