server:
  port: 8082

spring:
  application:
    name: JavaServiceApi

java-runner:
  docker:
    filePath: C:/Users/ciordan/JavaOnlineCompiler/openjdk_11.Dockerfile
    buildArgs:
      copyPathArg: COPY_PATH
    relativeCopyPath: ./generated/classes/
    container:
      timeoutMilliseconds: 30000

gotty:
  port: 8080